### ISSUE TITLE
Improve error message for direct reference to a function using a module prefix

### ISSUE THREAD

**Issue by oscols** [JonasHUL/mypy#10]
The function is using a module prefix. For example “if mod.func:”.

**Comment by JonasHUL** [comment]
![image](https://user-images.githubusercontent.com/67924458/221864096-be3bb7f3-05e0-4477-95c5-17ec01bde320.png)

Chnage the DirectRef part

**Comment by oscols** [comment]
This is in file "checker.py" ~line 5212
The message from message_registry is in file "message_registry.py" ~line 155

**Comment by oscols** [comment]
Slight misunderstanding, reopening issue
