### ISSUE TITLE
Improve error message for reference to a method

### ISSUE THREAD

**Issue by oscols** [JonasHUL/mypy#11]
The function is using a method. For example “if obj.method:”.

**Comment by JonasHUL** [comment]
![image](https://user-images.githubusercontent.com/67924458/221863686-f45c8544-4e6c-4e6e-a26c-88047973067e.png)

This task will focus on the second elif

**Comment by oscols** [comment]
Test for this requirement pass:
![image](https://user-images.githubusercontent.com/83168314/222158262-fe5bf59b-67d7-4455-aa51-1fe1d7577525.png)
