### ISSUE TITLE
Improve error message for reference to a variable/attribute

### ISSUE THREAD

**Issue by oscols** [JonasHUL/mypy#12]
The function is using a variable/attribute (Var node) with type Callable[...] (in this case we could show the name of the variable/attribute or the callable type).

**Comment by oscols** [comment]
This is in file "checker.py" ~line 5212
The message from message_registry is in file "message_registry.py" ~line 155

**Comment by BrionyMeng** [comment]
Test for this requirement pass.
![image](https://user-images.githubusercontent.com/96626549/222308372-0931127e-f616-4f81-97fd-7390dab17100.png)
